# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  deploy-sdist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Install Ubuntu system dependencies
      run: |
        sudo apt-get install -y --no-install-recommends ninja-build
    - name: Build DP-XGBoost
      shell: bash -l {0}
      run: |
        cd python-package
        python --version
        python setup.py sdist
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: python-package/dist/
  
  deploy-wheels-non-linux:
    runs-on: ${{ matrix.os }}
    env:
      TWINE_USERNAME: __token__
      TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
    strategy:
      matrix:
        os: [macos-10.15, windows-latest]
        python-version: ["3.8", "3.9"]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Install osx system dependencies
      if: matrix.os == 'macos-10.15'
      run: |
        brew install ninja libomp
    - name: Install Ubuntu system dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install -y --no-install-recommends ninja-build
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: test
    - name: Display Conda env
      shell: bash -l {0}
      run: |
        conda info
        conda list
    - name: Build DP-XGBoost
      shell: bash -l {0}
      run: |
        cd python-package
        python --version
        python setup.py bdist_wheel
    - name: Upload wheel
      run: |
        pip install twine
        twine upload python-package/dist/*
  
  deploy-wheels-manylinux:
    runs-on: ubuntu-latest
    container:
      image: manylinux_2_24_x86_64
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      volumes:
        - python-package:/python-package
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: test
    - name: Display Conda env
      shell: bash -l {0}
      run: |
        conda info
        conda list
    - name: Build DP-XGBoost
      shell: bash -l {0}
      run: |
        cd /python-package
        python --version
        python setup.py bdist_wheel
    - name: Upload wheel
      run: |
        pip install twine
        twine upload python-package/dist/*